import { Athlete } from "./Athlete";
import { Map } from "./Map";

export class Activities {
    constructor(
        public resource_state: number = 0,
        public athlete: Athlete = new Athlete(0, 0),
        public name: string = '',
        public distance: number = 0,
        public moving_time: number = 0,
        public elapsed_time: number = 0,
        public total_elevation_gain: number = 0,
        public type: string = '',
        public sport_type: string = '',
        public id: number = 0,
        public start_date: Date = new Date(),
        public start_date_local: Date = new Date(),
        public timezone: string = '',
        public utc_offset: number = 0,
        public location_city: string = '',
        public location_state: string = '',
        public location_country: string = '',
        public achievement_count: number = 0,
        public kudos_count: number = 0,
        public comment_count: number = 0,
        public athlete_count: number = 0,
        public photo_count: number = 0,
        public map: Map = new Map('', '', 0),
        public trainer: boolean = false,
        public commute: boolean = false,
        public manual: boolean = false,
        public privateActivity: boolean = false,
        public visibility: string = '',
        public flagged: boolean = false,
        public gear_id: string = '',
        public start_latlng: number[] = [],
        public end_latlng: number[] = [],
        public average_speed: number = 0,
        public max_speed: number = 0,
        public has_heartrate: boolean = false,
        public heartrate_opt_out: boolean = false,
        public display_hide_heartrate_option: boolean = false,
        public upload_id: number | null = null,
        public external_id: string = '',
        public from_accepted_tag: boolean = false,
        public pr_count: number = 0,
        public total_photo_count: number = 0,
        public has_kudoed: boolean = false,
        public average_watts: number | null = null,
        public kilojoules: number | null = null,
        public device_watts: boolean | null = null,
        public average_heartrate: number | null = null,
        public max_heartrate: number | null = null,
        public elev_high: number | null = null,
        public elev_low: number | null = null
    ) {}
}